## Features Dashboard

Here is where all post-processing of Landscape Analysis results takes place.

In [84]:
%load_ext autoreload
%autoreload 2

from FeaturesDashboard import FeaturesDashboard

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [85]:
dashboard = FeaturesDashboard("features_results", "algo_performance") # initialisation creates overall features df.
dashboard.overall_features_df

TypeError: __init__() missing 1 required positional argument: 'algo_perf_path'

In [ ]:

# Read features for specific problem.
problem_features = dashboard.get_problem_features_df("CTP1", "5", "glob")

In [ ]:
problem_features

,scr,fsr,corr_obj_min,corr_obj_max,corr_obj_range,skew_avg,skew_min,skew_max,skew_rnge,kurt_avg,...,corr_obj_uc_rk_max,corr_cv_ranks,rk_uc_mdl_r2,rk_uc_range_coeff,cv_mdl_r2,cv_range_coeff,H_max,eps_s,m0,eps05
0,0.0,1.0,-0.349811,-0.349811,0.0,0.031133,-0.005801,0.068067,0.073868,-0.693512,...,0.550385,0,0.852938,0.908419,0.852938,0.908419,0,NaN,0.0,NaN
1,0.0,1.0,-0.516616,-0.516616,0.0,0.160702,0.001984,0.319419,0.317436,-0.562628,...,0.457365,0,0.811871,2.095550,0.811871,2.095550,0,NaN,0.0,NaN
2,0.0,1.0,-0.331833,-0.331833,0.0,-0.095314,-0.191695,0.001066,0.192761,-0.895698,...,0.609389,0,0.913809,1.810678,0.913809,1.810678,0,NaN,0.0,NaN
3,0.0,1.0,-0.362028,-0.362028,0.0,-0.009469,-0.015985,-0.002952,0.013033,-0.534066,...,0.592363,0,0.916578,2.389223,0.916578,2.389223,0,NaN,0.0,NaN
4,0.0,1.0,-0.539802,-0.539802,0.0,-0.096552,-0.193763,0.000658,0.194421,-0.680728,...,0.544270,0,0.835422,0.980903,0.835422,0.980903,0,NaN,0.0,NaN
5,0.0,1.0,-0.351479,-0.351479,0.0,-0.061938,-0.121606,-0.002271,0.119335,-0.693733,...,0.531618,0,0.794691,1.619602,0.794691,1.619602,0,NaN,0.0,NaN
6,0.0,1.0,-0.420306,-0.420306,0.0,-0.164758,-0.327829,-0.001687,0.326142,-0.722597,...,0.522719,0,0.847336,3.750121,0.847336,3.750121,0,NaN,0.0,NaN
7,0.0,1.0,-0.440840,-0.440840,0.0,0.066672,0.001179,0.132166,0.130987,-0.799745,...,0.500156,0,0.812082,2.314052,0.812082,2.314052,0,NaN,0.0,NaN
8,0.0,1.0,-0.357756,-0.357756,0.0,0.043591,-0.007362,0.094544,0.101907,-0.843509,...,0.539808,0,0.878451,1.803822,0.878451,1.803822,0,NaN,0.0,NaN
9,0.0,1.0,-0.416094,-0.416094,0.0,0.022823,0.000932,0.044714,0.043781,-0.765712,...,0.550347,0,0.840448,2.744606,0.840448,2.744606,0,NaN,0.0,NaN
10,0.0,1.0,-0.343822,-0.343822,0.0,0.062247,0.001556,0.122939,0.121383,-0.916587,...,0.529396,0,0.800242,3.462423,0.800242,3.462423,0,NaN,0.0,NaN
11,0.0,1.0,-0.325929,-0.325929,0.0,0.177124,-0.003231,0.357478,0.360709,-0.280963,...,0.509035,0,0.720936,1.347735,0.720936,1.347735,0,NaN,0.0,NaN
12,0.0,1.0,-0.383090,-0.383090,0.0,0.033461,-0.003148,0.070071,0.073219,-0.976688,...,0.767891,0,0.883305,6.605346,0.883305,6.605346,0,NaN,0.0,NaN
13,0.0,1.0,-0.206373,-0.206373,0.0,-0.008230,-0.016487,0.000027,0.016514,-0.679682,...,0.617418,0,0.872854,2.052502,0.872854,2.052502,0,NaN,0.0,NaN
14,0.0,1.0,-0.473723,-0.473723,0.0,0.198490,-0.007198,0.404178,0.411377,-0.730120,...,0.449231,0,0.722929,2.538897,0.722929,2.538897,0,NaN,0.0,NaN
15,0.0,1.0,-0.258122,-0.258122,0.0,-0.063687,-0.124523,-0.002851,0.121672,-0.870154,...,0.608411,0,0.944543,1.356902,0.944543,1.356902,0,NaN,0.0,NaN
16,0.0,1.0,-0.323396,-0.323396,0.0,-0.030542,-0.063838,0.002754,0.066592,-1.009513,...,0.697648,0,0.885744,2.477189,0.885744,2.477189,0,NaN,0.0,NaN
17,0.0,1.0,-0.360852,-0.360852,0.0,0.074854,-0.002654,0.152362,0.155016,-0.892004,...,0.710838,0,0.838796,3.346685,0.838796,3.346685,0,NaN,0.0,NaN
18,0.0,1.0,-0.337234,-0.337234,0.0,0.142446,0.001493,0.283398,0.281905,-0.696207,...,0.720756,0,0.870655,5.899048,0.870655,5.899048,0,NaN,0.0,NaN
19,0.0,1.0,-0.385395,-0.385395,0.0,0.127132,0.001254,0.253009,0.251755,-0.659734,...,0.523984,0,0.851958,1.861676,0.851958,1.861676,0,NaN,0.0,NaN
20,0.0,1.0,-0.309427,-0.309427,0.0,0.015619,-0.002141,0.033379,0.035520,-0.896197,...,0.671397,0,0.865221,3.192635,0.865221,3.192635,0,NaN,0.0,NaN
21,0.0,1.0,-0.382718,-0.382718,0.0,0.016564,-0.003632,0.036760,0.040392,-0.650484,...,0.532638,0,0.807634,1.545184,0.807634,1.545184,0,NaN,0.0,NaN
22,0.0,1.0,-0.259910,-0.259910,0.0,0.000743,0.000594,0.000892,0.000298,-0.686824,...,0.568801,0,0.781193,2.342395,0.781193,2.342395,0,NaN,0.0,NaN
23,0.0,1.0,-0.274335,-0.274335,0.0,0.080338,-0.000130,0.160805,0.160935,-0.861654,...,0.585292,0,0.844248,3.073226,0.844248,3.073226,0,NaN,0.0,NaN
24,0.0,1.0,-0.314923,-0.314923,0.0,0.114166,0.003107,0.225224,0.222117,-0.985597,...,0.645506,0,0.818925,4.297150,0.818925,4.297150,0,NaN,0.0,NaN
25,0.0,1.0,-0.242328,-0.242328,0.0,-0.076735,-0.159857,0.006388,0.166245,-0.819454,...,0.605065,0,0.909057,1.400459,0.909057,1.400459,0,NaN,0.0,NaN
26,0.0,1.0,-0.379250,-0.379250,0.0,-0.086689,-0.170465,-0.002913,0.167553,-0.548073,...,0.714211,0,0.906588,5.408492,0.906588,5.408492,0,NaN,0.0,NaN
27,0.0,1.0,0.000000,0.000000,0.0,-0.075380,-0.147287,-0.003473,0.143814,-0.529475,...,0.747973,0,0.788389,1.562521,0.788389,1.562521,0,NaN,0.0,NaN
28,0.0,1.0,-0.463174,-0.463174,0.0,0.198448,-0.000550,0.397445,0.397995,-0.890904,...,0.606889,0,0.865959,4.340835,0.865959,4.340835,0,NaN,0.0,NaN
29,0.0,1.0,-0.365053,-0.365053,0.0,0.025476,0.005415,0.045536,0.040121,-0.442973,...,0.511795,0,0.790287,1.457439,0.790287,1.457439,0,NaN,0.0,NaN

In [ ]:
overall_features_no_sd = dashboard.get_overall_features_df(give_sd=False)
overall_features_no_sd

,Name,D,scr_glob_mean,fsr_glob_mean,corr_obj_min_glob_mean,corr_obj_max_glob_mean,corr_obj_range_glob_mean,skew_avg_glob_mean,skew_min_glob_mean,skew_max_glob_mean,...,inc_avg_aw_mean,lnd_avg_aw_mean,uhv_ss_avg_aw_mean,nuhv_avg_aw_mean,uhvd_avg_aw_mean,hv_ss_avg_aw_mean,nhv_avg_aw_mean,hvd_avg_aw_mean,bhv_avg_aw_mean,length_avg_aw_mean
0,CTP1_d5,5,0.0,1.000000,-0.349187,-0.349187,0.0,0.027424,-5.172227e-02,1.065711e-01,...,0.339184,0.090909,0.335132,0.343031,0.007899,0.335132,0.343031,0.007899,0.343031,5.900000
1,CTP2_d5,5,0.0,0.993333,-0.611698,-0.611698,0.0,0.198300,-1.425934e-03,3.980263e-01,...,0.405837,0.090909,0.370521,0.380648,0.010127,0.370521,0.380634,0.010113,0.380634,3.800000
2,MW1_d5,5,0.0,0.000027,-0.359937,-0.359937,0.0,-0.276992,-5.539838e-01,4.531263e-07,...,0.090986,0.090909,0.209394,0.217146,0.007752,0.001398,0.001410,0.000011,0.001410,11.175333
3,MW2_d5,5,0.0,0.007267,-0.137003,-0.137003,0.0,0.157226,4.531263e-07,3.144519e-01,...,0.094810,0.090909,0.449220,0.465527,0.016307,0.021339,0.021588,0.000249,0.021588,5.545333

In [ ]:
# Get features for analysis type.
global_overall_features = FeaturesDashboard.get_features_for_analysis_type(overall_features_no_sd, "glob")
global_overall_features

,Name,D,scr_glob_mean,fsr_glob_mean,corr_obj_min_glob_mean,corr_obj_max_glob_mean,corr_obj_range_glob_mean,skew_avg_glob_mean,skew_min_glob_mean,skew_max_glob_mean,...,corr_obj_uc_rk_max_glob_mean,corr_cv_ranks_glob_mean,rk_uc_mdl_r2_glob_mean,rk_uc_range_coeff_glob_mean,cv_mdl_r2_glob_mean,cv_range_coeff_glob_mean,H_max_glob_mean,eps_s_glob_mean,m0_glob_mean,eps05_glob_mean
0,CTP1_d5,5,0.0,1.000000,-0.349187,-0.349187,0.0,0.027424,-5.172227e-02,1.065711e-01,...,0.590753,0.000000,0.842436,2.666191,0.842436,2.666191,0.000000,NaN,0.000000,NaN
1,CTP2_d5,5,0.0,0.993333,-0.611698,-0.611698,0.0,0.198300,-1.425934e-03,3.980263e-01,...,0.497296,0.042465,0.826162,1.789556,0.826162,1.789556,0.034896,0.587254,0.004762,0.423757
2,MW1_d5,5,0.0,0.000027,-0.359937,-0.359937,0.0,-0.276992,-5.539838e-01,4.531263e-07,...,0.539809,1.000000,0.668148,18.286176,0.668148,18.286176,0.839910,0.898565,0.586928,0.275943
3,MW2_d5,5,0.0,0.007267,-0.137003,-0.137003,0.0,0.157226,4.531263e-07,3.144519e-01,...,0.644210,1.000000,0.376790,46.418396,0.376790,46.418396,0.833492,1.429763,0.538282,0.887221

In [ ]:
# Get features for benchmark suite.
ctp_features = FeaturesDashboard.get_features_for_suite(overall_features_no_sd, "CTP")
ctp_features

,Name,D,scr_glob_mean,fsr_glob_mean,corr_obj_min_glob_mean,corr_obj_max_glob_mean,corr_obj_range_glob_mean,skew_avg_glob_mean,skew_min_glob_mean,skew_max_glob_mean,...,inc_avg_aw_mean,lnd_avg_aw_mean,uhv_ss_avg_aw_mean,nuhv_avg_aw_mean,uhvd_avg_aw_mean,hv_ss_avg_aw_mean,nhv_avg_aw_mean,hvd_avg_aw_mean,bhv_avg_aw_mean,length_avg_aw_mean
0,CTP1_d5,5,0.0,1.000000,-0.349187,-0.349187,0.0,0.027424,-0.051722,0.106571,...,0.339184,0.090909,0.335132,0.343031,0.007899,0.335132,0.343031,0.007899,0.343031,5.9
1,CTP2_d5,5,0.0,0.993333,-0.611698,-0.611698,0.0,0.198300,-0.001426,0.398026,...,0.405837,0.090909,0.370521,0.380648,0.010127,0.370521,0.380634,0.010113,0.380634,3.8